### ISSUE TITLE
[QUESTION] Should i run it 

### ISSUE THREAD

**Issue by OdymarGamer** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#41]
Hi i am pretty much a noob and i was wondering i am on rootful palera1n and should i run it or revert install palera1n and then install . 
Sorry for the question if its dumb .

**Comment by Bubblemint864** [comment]
Not sure about rootful but I was on rootless before, it won't retain your tweaks but the advantage over palera1n is that sep works. You can export a list of your packages in sileo though some tweaks probably won't work since this jailbreak is rootless. 

If you currently have palera1n and want to switch make sure you have trollstore installed so you are able to install the IPA required for this jailbreak. Do keep in mind that there are a few issues such as in app browsers not working correctly, but asides from that it's been a very good experience for me.

**Comment by jthoward64** [comment]
Yeah I would recommend wiping and installing rootless palera1n (or some other method of getting trollstore)

**Comment by KpwnZ** [comment]
It would overwrite the files installed by previous jailbreak tool.

**Comment by KpwnZ** [comment]
Close as complete.
